
matrix:
  include:

   - dist: trusty
     sudo: true
     addons:
        postgresql: 9.3
        apt:
          packages:
            - postgresql-9.3-pgtap
            - postgresql-9.3-postgis-2.1

   - dist: xenial
     sudo: true
     addons:
        postgresql: 9.5
        apt:
          packages:
            - postgresql-9.5-pgtap
            - postgresql-9.5-postgis-2.3

before_script:
  - cd tests
  - psql -U postgres -c 'CREATE DATABASE travis_ci_test;' -U postgres
  - psql -U postgres -d travis_ci_test -c 'CREATE EXTENSION postgis;'
  - psql -U postgres -d travis_ci_test -c 'CREATE EXTENSION pgtap;' 
  - psql -U postgres -d travis_ci_test -af ../sql/01-create_schema.sql
#   - psql -U postgres -d travis_ci_test -af insert_test_data.sql

script:
  - psql -U postgres -d travis_ci_test -Xf base.sql
